name: Deploy Server to EC2

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy server folder to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "server/"
          target: "/home/ubuntu/Site-Analyse"

      - name: SSH and restart server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Site-Analyse/server
            npm install
            npm run build
            cp src/config/serviceAccountKey.json dist/config/serviceAccountKey.json
            cd src
            npx prisma migrate deploy
            npx prisma generate
            cd ..
            pm2 restart all || pm2 start dist/index.js --name site-analyse-server
